## Basic Configuration

baseurl = "https://bss.pages.dev"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Benjamin Buetikofer"
title = "Software Services"

theme = "hugo-goa"

## Hugo Built-in Features
enableRobotsTXT = true

## Site Settings
[params]
author = "Software Services"
intro = "Development and consulting"
description = "Now @Ricardo and @iOverlander. Previously @Microsoft, @Avaloq and @Sunrise."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Bütikofer Software Services"
keywords = "software,developer,consulting,services,bütikofer"

## Social Accounts
[params.social]
github = "bueti"
linkedin = "benjamin-bütikofer-59584b64"
twitter = "gran_viaje"
email = "ben@software-services.ch"


## Extras
[params.extra]
copyright = "© 2021. Bütikofer Software Services. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = false
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false

## Main Menu
#[[menu.main]]
#    name = "blog"
#    weight = 100
#    identifier = "blog"
#    url = "/blog/"
#[[menu.main]]
#    name = "about"
#    identifier = "about"
#    weight = 200
#    url = "/about/"
#[[menu.main]]
#    name = "coderag"
#    identifier = "coderag"
#    weight = 300
#    url = "/coderag/"
